// import "bootstrap/dist/css/bootstrap.min.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Greg's Weather",
  // TODO delete
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        /* TODO change style, imports */
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* TODO delete */}
        {/* <h1>Root Layout Text</h1> */}
        {children}
      </body>
    </html>
  );
}
